version: '3.7'
services:
  arma3:
    image: ghcr.io/flufflesamy/arma3server:latest
    build: .
    ports:
        - "2302:2302/udp" 
        - "2303:2303/udp" # Arma Server STEAM query port 
        - "2304:2304/udp" # Arma Server to STEAM master traffic
        - "2305:2305/udp"
        - "2306:2306/udp"
        # Uncomment if you want to use BattlEye
        # - "2344:2344" # BattlEye - arma31.battleye.com 
        # - "2345:2345/tcp" # BattlEye - arma31.battleye.com 
    volumes:
      - './arma3:/arma3'
      # Uncomment if you want to persistently store login data, 
      # ensure that it's owned by UID/GID 1000:1000
      - './userdata:/home/steam/Steam'
    env_file: .env
    restart: unless-stopped
