name: Publish Image
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v4
      - 
        name: Build image tag
        run: echo "IMAGE_TAG=$(git log -1 --pretty=%h)" >> $GITHUB_ENV 
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/flufflesamy/arma3server:${{ env.IMAGE_TAG }}
            ghcr.io/flufflesamy/arma3server:latest
          file: ./Dockerfile
          build-args: |
              IMAGE_TAG=${{ env.IMAGE_TAG }}
